[deps]
AbstractMCMC = "80f14c24-f653-4e6a-9b94-39d6b0f70001"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
AbstractMCMC = "3"
Documenter = "0.26"
julia = "1"
