name: Add Navbar

on:
  workflow_run:
    workflows: ["*"]  # add workflow names that generates docs in this list like `workflows: ["Docs Workflow", "Previews Workflow]`
    types: 
      - completed
  workflow_dispatch:  # Allows manual triggering

jobs:
  add-navbar:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Download insert_navbar.sh
        run: |
          curl -O https://raw.githubusercontent.com/TuringLang/turinglang.github.io/main/assets/scripts/insert_navbar.sh
          chmod +x insert_navbar.sh

      - name: Update Navbar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          
          # Update all HTML files in the current directory (gh-pages root)
          ./insert_navbar.sh .
          
          # Check if there are any changes
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "added navbar"
            git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" gh-pages
          else
            echo "No changes to commit"
          fi